# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly.io Deployment

on:
  push:
    branches:
      - main
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy to Fly.io
        required: false
        type: boolean

concurrency:
  group: fly-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
